#logging:
#  level:
#    org.springframework.web: ERROR
#    com.murava.bankscaling: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: app.log

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankscaling
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
  session:
    jdbc:
      initialize-schema: always

bank-rate: 10

debug: true

server:
  port: 8091
